# Generated by Django 3.1.3 on 2020-11-14 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectinfo',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.RemoveField(
            model_name='objectinfo',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='objectinfo',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='objectinfo',
            name='wheather1',
        ),
    ]
